### ISSUE TITLE
Which versions of Node.js did you use?

### ISSUE THREAD

**Issue by ghost** [noelhibbard/node-airplayhub#1]
I tried to install on Debian with Node.js 6.9.2, installed as documented on this site, running in multiple errors.

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

Which version and install method of Node.js did you use?

**Comment by noelhibbard** [comment]
Works perfect on 4.4 and 6.9.2. I actually loaded Debian Jessie in a VM yesterday to make sure I had all the dependencies documented in the readme properly. I installed node the same exact way you posted above.

But make sure you also update npm to the latest version:
`$ npm update -g npm`

And like in the readme:
`$ apt-get install -y build-essential git libavahi-compat-libdnssd-dev`

**Comment by ghost** [comment]
Thank you! Installation works fine now.
