### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by thebradbain** [noelhibbard/node-airplayhub#3]
Didn't know how else to contact you, but I wanted to say thanks for this amazing piece of software. I stumbled across your open [issue](https://github.com/mikebrady/shairport-sync/issues/384) on shairport-sync, and the problem (and solution!) you described was exactly what I was looking for, too.

It's amazing that all the pieces were essentially right in front of everyone, but it was you who put them together to make something complicated almost trivial. Thanks!

**Comment by noelhibbard** [comment]
I would say every 4 months or so for the past 4 years I go on the hunt for a solution like this and I've come close with other software, some commercial which I spent some money on but none of them were the perfect fit. I was aware of all the projects I am using in my solution. I have no idea why it took me so long to think of throwing them all together like I did.

I'm glad you are enjoying it. I know I have.
