### ISSUE TITLE
unable to choose other config file

### ISSUE THREAD

**Issue by roccogranata** [noelhibbard/node-airplayhub#7]
Unfortunately I'm unable to use the config file option. If I start "node-airplayhub --config /tmp/test.json" it stops with the following error (test.json is readable and valid, I copied it from config.json):

---

/usr/local/lib/node_modules/node-airplayhub/index.js:21
        configPath = path.join(__dirname, argv.config);
                         ^

TypeError: Cannot read property 'join' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/node-airplayhub/index.js:21:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

**Comment by noelhibbard** [comment]
Fixed. Thanks for the report.

**Comment by roccogranata** [comment]
Thank you for your work, but now I get a new error. If I start "node-airplayhub -c /etc/node-airplayhub.conf" it is looking for the config in the wrong path, it adds the base path /usr/local/lib/node_modules/node-airplayhub/ to the given one.

---

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/node-airplayhub/etc/node-airplayhub.conf'

**Comment by noelhibbard** [comment]
Fixed

**Comment by roccogranata** [comment]
Works for me now, thanks for fixing! 

And thank you very much for your work, this software is exactly what I was looking for.
