### ISSUE TITLE
AppleTV 4G stops playing

### ISSUE THREAD

**Issue by uberbruns** [noelhibbard/node-airplayhub#8]
Hi,

first, this is a great project. Thanks for the time and thanks for sharing.

Sadly, at this point my AppleTV 4G stops playing music within the first 5-10 minutes of switching to airplayhub's virtual speaker. The other speaker (Shairpoint Sync based) still plays music after that.

Furthermore I changed the `servername` but all devices still show the original `[AirPlay Hub]` name.

Any hints how I can solve these problems?

Thank you very much

Karsten

**Comment by noelhibbard** [comment]
I don't have an ATV4 to test with so I can't help much there. As for the servername. I just loaded up a new machine with Debian Jessie and then loaded node-airplayhub and I am not having problems changing the server name. I am using the --config option. If you don't use the --config option it will place the config file in the same folder as you have node-airplay hub installed. If you do a global install this path would typically be /usr/lib/node_modules/node-airplayhub/config.json. I am guessing you are editing the wrong config file. I just tested and I am able to change the server name with no problem.

**Comment by uberbruns** [comment]
Okay … I'll retest this evening. But since my zones are read correctly from the config-file I assume that node-airplayhib finds the configfile

**Comment by noelhibbard** [comment]
True, but you may have multiple config files in multiple locations, for example maybe you installed it locally and later installed globally so you ended up with two files and your editing the wrong file?

**Comment by uberbruns** [comment]
I use Docker and the Dockerfile adds the config.json only a single time to the users home dir. Not sure how this could generate multiple config files.

**Comment by uberbruns** [comment]
It seems to be a problem with `node_airtunes`. When I use the library directly it still stops after a few minutes.
